/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

===============================================================================
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold_dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold_dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- How many products were launched each year
SELECT YEAR(start_date) AS launch_year, COUNT(*) AS product_count
FROM gold_dim_products
WHERE start_date IS NOT NULL
GROUP BY YEAR(start_date)
ORDER BY launch_year;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Most frequently sold products by quantity 
SELECT dp.category, SUM(fs.quantity) AS total_quantity
FROM gold_fact_sales fs
JOIN gold_dim_products dp ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_quantity DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


-- Sales by gender across different countries 
SELECT
    dc.country,
    SUM(CASE WHEN dc.gender = 'Male' THEN fs.sales_amount ELSE 0 END) AS male_sales,
    SUM(CASE WHEN dc.gender = 'Female' THEN fs.sales_amount ELSE 0 END) AS female_sales,
    SUM(CASE WHEN dc.gender = 'n/a' THEN fs.sales_amount ELSE 0 END) AS 'N/A'
FROM gold_fact_sales fs
JOIN gold_dim_customers dc ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY dc.country;



